inputs_def:
  - handle: df
    json_schema:
      contentMediaType: oomol/var
  - handle: x_column
    json_schema:
      type: string
    nullable: true
    value:
  - handle: y_columns
    json_schema:
      type: array
      items:
        type: string
    value:
    nullable: true
  - handle: chart_title
    json_schema:
      type: string
    value:
    nullable: true
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Stacked Area Chart
icon: ":fa6-solid:chart-area:"
