inputs_def:
  - handle: xlsx
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Excel to df
icon: ":carbon:port-input:"
