ui:
  default_width: 450
inputs_def:
  - handle: df
    description: Input
    json_schema:
      contentMediaType: oomol/var
  - handle: preview
    json_schema:
      type: boolean
  - handle: column_name
    json_schema:
      type: string
outputs_def:
  - handle: df
    description: Output
    json_schema:
      contentMediaType: oomol/var
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Delete Column by Name
icon: ":carbon:delete:"
