inputs_def:
  - handle: df
    description: Input
    json_schema:
      contentMediaType: oomol/var
  - handle: save_dir
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
  - handle: name
    json_schema:
      type: string
    nullable: true
    value:
outputs_def:
  - handle: address
    description: Output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: DF to excel
icon: ":simple-icons:microsoftexcel:"
